#!/bin/bash
LOG_FILE="${TRIM_PKGVAR}/info.log"
DB_FILE="${TRIM_PKGVAR}/filebrowser.db"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

rm -f "${DB_FILE}"
log_msg "清除旧数据库"

${TRIM_APPDEST}/bin/filebrowser -d ${DB_FILE} config init
if [ $? -ne 0 ]; then
    log_msg "错误: 数据库初始化失败！"
    exit 1
fi
    
${TRIM_APPDEST}/bin/filebrowser -d ${DB_FILE} config set --locale zh-cn
if [ $? -ne 0 ]; then
    log_msg "错误: 配置设置失败！"
    exit 1
fi
    
${TRIM_APPDEST}/bin/filebrowser -d ${DB_FILE} users add $fb_admin $fb_password --perm.admin
if [ $? -ne 0 ]; then
    log_msg "错误: 用户创建失败！"
    exit 1
fi
    
log_msg "数据库已成功重置"

exit 0
