#!/bin/bash
LOG_FILE="${TRIM_PKGVAR}/info.log"
DB_FILE="${TRIM_PKGVAR}/filebrowser.db"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

if [ -f "$DB_FILE" ]; then
    log_msg "数据库文件 $DB_FILE 已存在，跳过初始化。"
else
    log_msg "未检测到数据库文件，开始初始化..."
    ${TRIM_APPDEST}/bin/filebrowser -d ${DB_FILE} config init
    if [ $? -ne 0 ]; then
        echo "错误: 数据库初始化失败！" > ${TRIM_TEMP_LOGFILE}
        exit 1
    fi
    
    ${TRIM_APPDEST}/bin/filebrowser -d ${DB_FILE} config set --locale zh-cn
    if [ $? -ne 0 ]; then
        echo "错误: 配置设置失败！" > ${TRIM_TEMP_LOGFILE}
        exit 1
    fi
    
    ${TRIM_APPDEST}/bin/filebrowser -d ${DB_FILE} users add $fb_admin $fb_password --perm.admin
    if [ $? -ne 0 ]; then
        echo "错误: 用户创建失败！" > ${TRIM_TEMP_LOGFILE}
        exit 1
    fi
    
    log_msg "数据库已成功初始化并完成配置"
fi

exit 0
