name: Build DeepSeek Harness

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x64
            runner: ubuntu-24.04
            node_url: https://nodejs.org/dist/v24.19.0/node-v24.19.0-linux-x64.tar.xz
          - arch: arm64
            runner: ubuntu-24.04-arm
            node_url: https://nodejs.org/dist/v24.19.0/node-v24.19.0-linux-arm64.tar.xz

    steps:
      - name: Checkout deepseek-harness
        uses: actions/checkout@v7
        with:
          repository: deepseek-ai/deepseek-harness
          path: server

      - name: Download and setup Node.js
        run: |
          # 下载 Node.js 二进制
          curl -L -o node.tar.xz ${{ matrix.node_url }}
          tar -xf node.tar.xz
          mv node-v24.19.0-linux-* node

          # 将 node/bin 加入 PATH（全局可用）
          echo "$(pwd)/node/bin" >> $GITHUB_PATH

          # 设置 pnpm 的家目录和存储目录（全部放在 node/.pnpm 下）
          echo "PNPM_HOME=$(pwd)/.pnpm" >> $GITHUB_ENV

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        working-directory: server
        run: pnpm install

      - name: Build project
        working-directory: server
        run: pnpm run build


      - name: Prune to production dependencies and clean sources
        working-directory: server
        run: |
           rm -rf .github .git

      - name: Compress entire node directory
        run: |
          tar -czf node.tar.gz node
          tar -czf server.tar.gz server

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: server-${{ matrix.arch }}
          path: |
            server.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: node-${{ matrix.arch }}
          path: |
            node.tar.gz
