name: Build localsend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: 克隆源码
        uses: actions/checkout@v7
        with:
          repository: localsend/web
          path: web-src

      - name: 安装依赖
        working-directory: ./web-src
        run: |
          npm install -g pnpm
          pnpm install --ignore-scripts --frozen-lockfile
          yes | pnpm approve-builds || true
          pnpm install --frozen-lockfile
          pnpm run generate

      - name: 上传构建产物
        uses: actions/upload-artifact@v7
        with:
          name: localsend
          path: ./web-src/dist
